### PR TITLE
fix #12

### LINKED ISSUE #12: plumber is invalid when error occurred
if i add a comma to the end of a line, this plugin will throw a YAMLException which will break gulp watch.
i tried to add gulp-plumber to prevent it, but it doesn't effect
how could i solve it

image
image

### PR DESCRIPTION
**Pull request by zz5840**
thanks for helping

### CODE REVIEW

**Comment by ehmicky** [comment]
@crissdev @zz5840 It seems to me that with this fix, YAML files that are only a top-level `null` or `false` value will not be parsed correctly.

**Comment by zz5840** [comment]
@ehmicky how about change https://github.com/crissdev/gulp-yaml/pull/13/files#diff-168726dbe96b3ce427e7fedce31bb0bcR25 to `file.contents = result ? result : ""`

**Comment by ehmicky** [comment]
I am not sure whether `file.contents` should be set to an empty string if an error arises. Also this does not account for when the YAML document is only the value `!!js/undefined`.

**Comment by zz5840** [comment]
@ehmicky Oh sorry, `file.contents` should be a Buffer. I just want to fix the bug that gulp-plumber is invalid when an error occurs and it do affect.

**Comment by ehmicky** [comment]
Just to be precise for fixing this issue: `file.contents` can actually be a `Buffer`, a `Stream` or `null`.

**Comment by zz5840** [comment]
@ehmicky I'm sorry for my careless, I just want to say `file.contents` should not be a string, so the code above are wrong

**Comment by crissdev** [comment]
@ehmicky, Proposed changes are in [empty-content-on-error branch](https://github.com/crissdev/gulp-yaml/tree/empty-content-on-error) - An empty string is returned in case of an error. Please have a look at it if you have time. Thanks.

@zz5840 I tried to reproduce #12 but without luck. The project I used to test it is available here https://github.com/crissdev/gulp-yaml-empty-content-on-error.

**Comment by ehmicky** [comment]
@crissdev Just did!

**Comment by crissdev** [comment]
Thanks for your prompt response @ehmicky

**Pull request closed without merging**
