### PR TITLE
Feature/upgrade version

### PR DESCRIPTION
**Pull request by ehmicky**
Upgrade `npm` version and update `CHANGELOG`.

(I don't have collaborator access to `npm` so I cannot publish the module myself).

### CODE REVIEW

**Comment by ehmicky** [comment]
Done.

**Comment by crissdev** [comment]
@ehmicky Tags gets applied only on master branch because other branches may be rebased.

**Comment by crissdev** [comment]
Published v2.0.0

**Comment by ehmicky** [comment]
Will do next time for the tags.

I also added a GitHub release description: https://github.com/crissdev/gulp-yaml/releases

I am myself using RSS to track GitHub repos and GitHub release descriptions show up in RSS feed, which is nice.

**Pull request closed without merging**
